# bootstrapping an AWS account
Parameters:
  TemplateBucketName:
    Description: "Bucket name where the templates are uploaded"
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
  EnvironmentName:
    Description: "Used to name the VPC that is created"
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "dev"
  NetworkStackName:
    Description: "Name of an active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "DefaultNetworkStack"
  DefaultTaskExecutionRolePolicyName:
    Description: "default task execution role policy name."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-task-execution-role-policy"
  DefaultTaskExecutionRoleName:
    Description: "default task execution role name."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-task-execution-role"
  DefaultTaskRoleName:
    Description: "default task role name."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-task-role"
  DefaultApplicationLoadBalancerSecurityGroupName:
    Description: "default name for application load balancer security group."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-application-lb-sg"
  DefaultApplicationLoadBalancerName:
    Description: "default name for application load balancer security group."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-application-lb"
  DefaultServiceSecurityGroupName:
    Description: "default name for service security group."
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "default-service-sg"

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucketName}/VPC.yaml
      TimeoutInMinutes: "60"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  ECSClusterDefaults:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucketName}/ECS_CLUSTER_DEFAULTS.yaml
      TimeoutInMinutes: "60"
      Parameters:
        ECRPublicRepoLocation: "s1k9c2t7/mast-lambda:latest"
  defaultTaskExecutionRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Ref DefaultTaskExecutionRolePolicyName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
            Resource: "*"
  taskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: "String"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
        - !Ref defaultTaskExecutionRolePolicy
      RoleName: !Ref DefaultTaskExecutionRoleName
      Tags:
        - Key: "used_by"
          Value: "mast"
    DependsOn: "defaultTaskExecutionRolePolicy"

  # defaultTaskRolePolicy:
  #   Type: "AWS::IAM::ManagedPolicy"
  #   Properties:
  #     ManagedPolicyName: "default-task-role-policy"
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - "s3:GetObject"
  #           Resource: "*"
  taskRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: "String"
      # ManagedPolicyArns:
      #   - !Ref defaultTaskRolePolicy
      RoleName: !Ref DefaultTaskRoleName
      Tags:
        - Key: "used_by"
          Value: "mast"
    # DependsOn: "defaultTaskRolePolicy"

  defaultApplicationLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "String"
      GroupName: !Ref DefaultApplicationLoadBalancerSecurityGroupName
      # SecurityGroupEgress:
      #   - Egress
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "String"
          FromPort: 0
          IpProtocol: "tcp"
          ToPort: 65534
      Tags:
        - Key: "used_by"
          Value: "mast"
      VpcId: !GetAtt VPC.Outputs.VPC # { "Fn::ImportValue": { "Fn::Sub": "${NetworkStackName}-VPCId" } }
  defaultApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: "ipv4"
      # LoadBalancerAttributes:
      #   - LoadBalancerAttribute
      Name: !Ref DefaultApplicationLoadBalancerName
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref defaultApplicationLoadBalancerSecurityGroup
      # SubnetMappings:
      #   - SubnetMapping
      Subnets: { "Fn::Split": [
              ",",
              !GetAtt VPC.Outputs.PublicSubnets,
              # {
              #   "Fn::ImportValue":
              #     { "Fn::Sub": "${NetworkStackName}-PublicSubnets" },
              # },
            ] }
      Tags:
        - Key: "used_by"
          Value: "mast"
      Type: "application"
    DependsOn: "defaultApplicationLoadBalancerSecurityGroup"

  defaultApplicationLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      # AlpnPolicy:
      #   - String
      # Certificates:
      #   - Certificate
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: "text/plain"
            MessageBody: "naughty naughty"
            StatusCode: "503"
      LoadBalancerArn: !Ref defaultApplicationLoadBalancer
      Port: 8080
      Protocol: HTTP
      # SslPolicy: String

  defaultServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "String"
      GroupName: !Ref DefaultServiceSecurityGroupName
      # SecurityGroupEgress:
      #   - Egress
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref defaultApplicationLoadBalancerSecurityGroup
          Description: "String"
          FromPort: 0
          IpProtocol: "tcp"
          ToPort: 65534
      Tags:
        - Key: "used_by"
          Value: "mast"
      VpcId: !GetAtt VPC.Outputs.VPC # { "Fn::ImportValue": { "Fn::Sub": "${NetworkStackName}-VPCId" } }

Outputs:
  LoadBalancerDomainName:
    Description: A reference to the created VPC
    Value: !GetAtt defaultApplicationLoadBalancer.DNSName
    Export:
      {
        "Name":
          { "Fn::Sub": "${AWS::StackName}-defaultApplicationLoadBalancer" },
      }
  LoadBalancerListenerId:
    Description: A reference to the created VPC
    Value: !Ref defaultApplicationLoadBalancerListener
    Export:
      {
        "Name":
          {
            "Fn::Sub": "${AWS::StackName}-defaultApplicationLoadBalancerListener",
          },
      }
  TaskExecutionRoleArn:
    Description: A reference to the created VPC
    Value: !Ref taskExecutionRole
    Export: { "Name": { "Fn::Sub": "${AWS::StackName}-taskExecutionRole" } }
  TaskRoleArn:
    Description: A reference to the created VPC
    Value: !Ref taskRole
    Export: { "Name": { "Fn::Sub": "${AWS::StackName}-taskRole" } }
  ServiceSecurityGroupId:
    Description: A reference to the created VPC
    Value: !Ref defaultServiceSecurityGroup
    Export:
      { "Name": { "Fn::Sub": "${AWS::StackName}-defaultServiceSecurityGroup" } }
  PrivateECRPullthrough:
    Description: PrivateECRPullthrough
    Value: !GetAtt ECSClusterDefaults.Outputs.PrivateECRMastLambdaLocation
  PrivateECRLoginCommand:
    Description: PrivateECRLoginCommand
    Value: !GetAtt ECSClusterDefaults.Outputs.PrivateECRLoginCommand
  VPCId:
    Description: Vpc IS
    Value: !GetAtt VPC.Outputs.VPC
  PrivateSubnets:
    Description: PrivateSubnets
    Value: !GetAtt VPC.Outputs.PrivateSubnets
  PublicSubnets:
    Description: PublicSubnets
    Value: !GetAtt VPC.Outputs.PublicSubnets
